# permissions for end users to view externalagents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: externalagent-viewer-role
rules:
- apiGroups:
  - base.cd.klovercloud.com
  resources:
  - externalagents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - base.cd.klovercloud.com
  resources:
  - externalagents/status
  verbs:
  - get
