# permissions for end users to view klovercloudcds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klovercloudcd-viewer-role
rules:
- apiGroups:
  - base.cd.klovercloud.com
  resources:
  - klovercloudcds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - base.cd.klovercloud.com
  resources:
  - klovercloudcds/status
  verbs:
  - get
