# permissions for end users to edit klovercloudcds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: klovercloudcd-editor-role
rules:
- apiGroups:
  - base.cd.klovercloud.com
  resources:
  - klovercloudcds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.cd.klovercloud.com
  resources:
  - klovercloudcds/status
  verbs:
  - get
